apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-kustomize
spec:
  params:
    - name: KUSTOMIZE_PATH
      description: Path to the kustomization.yaml to deploy.
    - name: IMAGE_TAG
      description: The tag of the image to set in kustomization.
    - name: NAMESPACE
      description: Target namespace.
  workspaces:
    - name: source
  steps:
    - name: set-image-and-deploy
      image: line/kubectl-kustomize:latest
      workingDir: $(workspaces.source.path)/$(params.KUSTOMIZE_PATH)
      script: |
        #!/bin/sh
        kustomize edit set image questions=$(params.IMAGE_TAG)
        kustomize build . | kubectl apply -n $(params.NAMESPACE) -f -
