apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-kubectl
  namespace: tekton-pipelines
spec:
  description: >-
    Эта задача применяет манифесты Kubernetes в указанном пространстве имен.
  params:
    - name: NAMESPACE
      description: Пространство имен (dev или prod).
    - name: MANIFESTS_DIR
      description: Путь к манифестам в рабочем пространстве.
      default: k8s/app
    - name: IMAGE
      description: Имя образа для замены в деплойменте.
  workspaces:
    - name: source
  steps:
    - name: kubectl-apply
      workingDir: $(workspaces.source.path)
      image: bitnami/kubectl:latest
      script: |
        # Заменяем образ в деплойменте (если используем шаблонизацию или kustomize)
        # В данном примере просто заменяем строку IMAGE_PLACEHOLDER
        sed -i "s|IMAGE_PLACEHOLDER|$(params.IMAGE)|g" $(params.MANIFESTS_DIR)/deployment.yaml
        
        kubectl apply -f $(params.MANIFESTS_DIR) -n $(params.NAMESPACE)
