apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: questions-dev-run-
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: app-cicd-pipeline
  params:
    - name: REPO_URL
      value: "https://github.com/mobqom/questions.git"
    - name: REPO_REVISION
      value: "main"
    - name: IMAGE
      value: "ghcr.io/mobqom/questions" # Измените на ваш реестр
    - name: TARGET_NAMESPACE
      value: "dev"
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
