// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/v1/option.proto

package optionsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Option struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	QuestionId    uint32                 `protobuf:"varint,3,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Option) Reset() {
	*x = Option{}
	mi := &file_proto_v1_option_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Option) ProtoMessage() {}

func (x *Option) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_option_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Option.ProtoReflect.Descriptor instead.
func (*Option) Descriptor() ([]byte, []int) {
	return file_proto_v1_option_proto_rawDescGZIP(), []int{0}
}

func (x *Option) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Option) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Option) GetQuestionId() uint32 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

type AddOptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	QuestionId    uint32                 `protobuf:"varint,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOptionRequest) Reset() {
	*x = AddOptionRequest{}
	mi := &file_proto_v1_option_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOptionRequest) ProtoMessage() {}

func (x *AddOptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_option_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOptionRequest.ProtoReflect.Descriptor instead.
func (*AddOptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_option_proto_rawDescGZIP(), []int{1}
}

func (x *AddOptionRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddOptionRequest) GetQuestionId() uint32 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

type AddOptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Option        *Option                `protobuf:"bytes,1,opt,name=option,proto3" json:"option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOptionResponse) Reset() {
	*x = AddOptionResponse{}
	mi := &file_proto_v1_option_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOptionResponse) ProtoMessage() {}

func (x *AddOptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_option_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOptionResponse.ProtoReflect.Descriptor instead.
func (*AddOptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_option_proto_rawDescGZIP(), []int{2}
}

func (x *AddOptionResponse) GetOption() *Option {
	if x != nil {
		return x.Option
	}
	return nil
}

type FindOptionsByQuestionIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    uint32                 `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindOptionsByQuestionIdRequest) Reset() {
	*x = FindOptionsByQuestionIdRequest{}
	mi := &file_proto_v1_option_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindOptionsByQuestionIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOptionsByQuestionIdRequest) ProtoMessage() {}

func (x *FindOptionsByQuestionIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_option_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOptionsByQuestionIdRequest.ProtoReflect.Descriptor instead.
func (*FindOptionsByQuestionIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_option_proto_rawDescGZIP(), []int{3}
}

func (x *FindOptionsByQuestionIdRequest) GetQuestionId() uint32 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

type FindOptionsByQuestionIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       []*Option              `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindOptionsByQuestionIdResponse) Reset() {
	*x = FindOptionsByQuestionIdResponse{}
	mi := &file_proto_v1_option_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindOptionsByQuestionIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOptionsByQuestionIdResponse) ProtoMessage() {}

func (x *FindOptionsByQuestionIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_option_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOptionsByQuestionIdResponse.ProtoReflect.Descriptor instead.
func (*FindOptionsByQuestionIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_option_proto_rawDescGZIP(), []int{4}
}

func (x *FindOptionsByQuestionIdResponse) GetOptions() []*Option {
	if x != nil {
		return x.Options
	}
	return nil
}

var File_proto_v1_option_proto protoreflect.FileDescriptor

const file_proto_v1_option_proto_rawDesc = "" +
	"\n" +
	"\x15proto/v1/option.proto\x12\n" +
	"options.v1\"S\n" +
	"\x06Option\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1f\n" +
	"\vquestion_id\x18\x03 \x01(\rR\n" +
	"questionId\"M\n" +
	"\x10AddOptionRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\rR\n" +
	"questionId\"?\n" +
	"\x11AddOptionResponse\x12*\n" +
	"\x06option\x18\x01 \x01(\v2\x12.options.v1.OptionR\x06option\"A\n" +
	"\x1eFindOptionsByQuestionIdRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\rR\n" +
	"questionId\"O\n" +
	"\x1fFindOptionsByQuestionIdResponse\x12,\n" +
	"\aoptions\x18\x01 \x03(\v2\x12.options.v1.OptionR\aoptions2\xce\x01\n" +
	"\x0eOptionsService\x12H\n" +
	"\tAddOption\x12\x1c.options.v1.AddOptionRequest\x1a\x1d.options.v1.AddOptionResponse\x12r\n" +
	"\x17FindOptionsByQuestionId\x12*.options.v1.FindOptionsByQuestionIdRequest\x1a+.options.v1.FindOptionsByQuestionIdResponseB7Z5github.com/mobqom/questions/proto/v1/option;optionsv1b\x06proto3"

var (
	file_proto_v1_option_proto_rawDescOnce sync.Once
	file_proto_v1_option_proto_rawDescData []byte
)

func file_proto_v1_option_proto_rawDescGZIP() []byte {
	file_proto_v1_option_proto_rawDescOnce.Do(func() {
		file_proto_v1_option_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_option_proto_rawDesc), len(file_proto_v1_option_proto_rawDesc)))
	})
	return file_proto_v1_option_proto_rawDescData
}

var file_proto_v1_option_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_v1_option_proto_goTypes = []any{
	(*Option)(nil),                          // 0: options.v1.Option
	(*AddOptionRequest)(nil),                // 1: options.v1.AddOptionRequest
	(*AddOptionResponse)(nil),               // 2: options.v1.AddOptionResponse
	(*FindOptionsByQuestionIdRequest)(nil),  // 3: options.v1.FindOptionsByQuestionIdRequest
	(*FindOptionsByQuestionIdResponse)(nil), // 4: options.v1.FindOptionsByQuestionIdResponse
}
var file_proto_v1_option_proto_depIdxs = []int32{
	0, // 0: options.v1.AddOptionResponse.option:type_name -> options.v1.Option
	0, // 1: options.v1.FindOptionsByQuestionIdResponse.options:type_name -> options.v1.Option
	1, // 2: options.v1.OptionsService.AddOption:input_type -> options.v1.AddOptionRequest
	3, // 3: options.v1.OptionsService.FindOptionsByQuestionId:input_type -> options.v1.FindOptionsByQuestionIdRequest
	2, // 4: options.v1.OptionsService.AddOption:output_type -> options.v1.AddOptionResponse
	4, // 5: options.v1.OptionsService.FindOptionsByQuestionId:output_type -> options.v1.FindOptionsByQuestionIdResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_v1_option_proto_init() }
func file_proto_v1_option_proto_init() {
	if File_proto_v1_option_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_option_proto_rawDesc), len(file_proto_v1_option_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_option_proto_goTypes,
		DependencyIndexes: file_proto_v1_option_proto_depIdxs,
		MessageInfos:      file_proto_v1_option_proto_msgTypes,
	}.Build()
	File_proto_v1_option_proto = out.File
	file_proto_v1_option_proto_goTypes = nil
	file_proto_v1_option_proto_depIdxs = nil
}
