// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/v1/option.proto

package optionsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OptionsService_AddOption_FullMethodName               = "/options.v1.OptionsService/AddOption"
	OptionsService_FindOptionsByQuestionId_FullMethodName = "/options.v1.OptionsService/FindOptionsByQuestionId"
)

// OptionsServiceClient is the client API for OptionsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OptionsServiceClient interface {
	AddOption(ctx context.Context, in *AddOptionRequest, opts ...grpc.CallOption) (*AddOptionResponse, error)
	FindOptionsByQuestionId(ctx context.Context, in *FindOptionsByQuestionIdRequest, opts ...grpc.CallOption) (*FindOptionsByQuestionIdResponse, error)
}

type optionsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOptionsServiceClient(cc grpc.ClientConnInterface) OptionsServiceClient {
	return &optionsServiceClient{cc}
}

func (c *optionsServiceClient) AddOption(ctx context.Context, in *AddOptionRequest, opts ...grpc.CallOption) (*AddOptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddOptionResponse)
	err := c.cc.Invoke(ctx, OptionsService_AddOption_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *optionsServiceClient) FindOptionsByQuestionId(ctx context.Context, in *FindOptionsByQuestionIdRequest, opts ...grpc.CallOption) (*FindOptionsByQuestionIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindOptionsByQuestionIdResponse)
	err := c.cc.Invoke(ctx, OptionsService_FindOptionsByQuestionId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OptionsServiceServer is the server API for OptionsService service.
// All implementations must embed UnimplementedOptionsServiceServer
// for forward compatibility.
type OptionsServiceServer interface {
	AddOption(context.Context, *AddOptionRequest) (*AddOptionResponse, error)
	FindOptionsByQuestionId(context.Context, *FindOptionsByQuestionIdRequest) (*FindOptionsByQuestionIdResponse, error)
	mustEmbedUnimplementedOptionsServiceServer()
}

// UnimplementedOptionsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOptionsServiceServer struct{}

func (UnimplementedOptionsServiceServer) AddOption(context.Context, *AddOptionRequest) (*AddOptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddOption not implemented")
}
func (UnimplementedOptionsServiceServer) FindOptionsByQuestionId(context.Context, *FindOptionsByQuestionIdRequest) (*FindOptionsByQuestionIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindOptionsByQuestionId not implemented")
}
func (UnimplementedOptionsServiceServer) mustEmbedUnimplementedOptionsServiceServer() {}
func (UnimplementedOptionsServiceServer) testEmbeddedByValue()                        {}

// UnsafeOptionsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OptionsServiceServer will
// result in compilation errors.
type UnsafeOptionsServiceServer interface {
	mustEmbedUnimplementedOptionsServiceServer()
}

func RegisterOptionsServiceServer(s grpc.ServiceRegistrar, srv OptionsServiceServer) {
	// If the following call panics, it indicates UnimplementedOptionsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OptionsService_ServiceDesc, srv)
}

func _OptionsService_AddOption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptionsServiceServer).AddOption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OptionsService_AddOption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptionsServiceServer).AddOption(ctx, req.(*AddOptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OptionsService_FindOptionsByQuestionId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOptionsByQuestionIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptionsServiceServer).FindOptionsByQuestionId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OptionsService_FindOptionsByQuestionId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptionsServiceServer).FindOptionsByQuestionId(ctx, req.(*FindOptionsByQuestionIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OptionsService_ServiceDesc is the grpc.ServiceDesc for OptionsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OptionsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "options.v1.OptionsService",
	HandlerType: (*OptionsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddOption",
			Handler:    _OptionsService_AddOption_Handler,
		},
		{
			MethodName: "FindOptionsByQuestionId",
			Handler:    _OptionsService_FindOptionsByQuestionId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/option.proto",
}
