apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-cd-pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: revision
      type: string
      default: main
    - name: image-name
      type: string
    - name: kustomize-path
      type: string
    - name: namespace
      type: string
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
    - name: build-image
      taskRef:
        name: build-image
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: $(params.image-name)
    - name: deploy
      taskRef:
        name: deploy-kustomize
      runAfter:
        - build-image
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: KUSTOMIZE_PATH
          value: $(params.kustomize-path)
        - name: IMAGE_TAG
          value: $(params.image-name)
        - name: NAMESPACE
          value: $(params.namespace)
