apiVersion: apps/v1
kind: Deployment
metadata:
  name: questions-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: questions
  template:
    metadata:
      labels:
        app: questions
    spec:
      containers:
      - name: app
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: questions-service
spec:
  selector:
    app: questions
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP
