// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/v1/question.proto

package questionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Game          string                 `protobuf:"bytes,3,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_proto_v1_question_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_question_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_proto_v1_question_proto_rawDescGZIP(), []int{0}
}

func (x *Question) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Question) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Question) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

type FindAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllRequest) Reset() {
	*x = FindAllRequest{}
	mi := &file_proto_v1_question_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllRequest) ProtoMessage() {}

func (x *FindAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_question_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllRequest.ProtoReflect.Descriptor instead.
func (*FindAllRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_question_proto_rawDescGZIP(), []int{1}
}

type FindAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*Question            `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllResponse) Reset() {
	*x = FindAllResponse{}
	mi := &file_proto_v1_question_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllResponse) ProtoMessage() {}

func (x *FindAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_question_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllResponse.ProtoReflect.Descriptor instead.
func (*FindAllResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_question_proto_rawDescGZIP(), []int{2}
}

func (x *FindAllResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

type AddQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Game          string                 `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddQuestionRequest) Reset() {
	*x = AddQuestionRequest{}
	mi := &file_proto_v1_question_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddQuestionRequest) ProtoMessage() {}

func (x *AddQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_question_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddQuestionRequest.ProtoReflect.Descriptor instead.
func (*AddQuestionRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_question_proto_rawDescGZIP(), []int{3}
}

func (x *AddQuestionRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddQuestionRequest) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

type AddQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      *Question              `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddQuestionResponse) Reset() {
	*x = AddQuestionResponse{}
	mi := &file_proto_v1_question_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddQuestionResponse) ProtoMessage() {}

func (x *AddQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_question_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddQuestionResponse.ProtoReflect.Descriptor instead.
func (*AddQuestionResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_question_proto_rawDescGZIP(), []int{4}
}

func (x *AddQuestionResponse) GetQuestion() *Question {
	if x != nil {
		return x.Question
	}
	return nil
}

type FindRandomQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRandomQuestionRequest) Reset() {
	*x = FindRandomQuestionRequest{}
	mi := &file_proto_v1_question_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRandomQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRandomQuestionRequest) ProtoMessage() {}

func (x *FindRandomQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_question_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRandomQuestionRequest.ProtoReflect.Descriptor instead.
func (*FindRandomQuestionRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_question_proto_rawDescGZIP(), []int{5}
}

func (x *FindRandomQuestionRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type FindRandomQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      *Question              `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRandomQuestionResponse) Reset() {
	*x = FindRandomQuestionResponse{}
	mi := &file_proto_v1_question_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRandomQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRandomQuestionResponse) ProtoMessage() {}

func (x *FindRandomQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_question_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRandomQuestionResponse.ProtoReflect.Descriptor instead.
func (*FindRandomQuestionResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_question_proto_rawDescGZIP(), []int{6}
}

func (x *FindRandomQuestionResponse) GetQuestion() *Question {
	if x != nil {
		return x.Question
	}
	return nil
}

type FindByGameIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByGameIdRequest) Reset() {
	*x = FindByGameIdRequest{}
	mi := &file_proto_v1_question_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByGameIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByGameIdRequest) ProtoMessage() {}

func (x *FindByGameIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_question_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByGameIdRequest.ProtoReflect.Descriptor instead.
func (*FindByGameIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_question_proto_rawDescGZIP(), []int{7}
}

func (x *FindByGameIdRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type FindByGameIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*Question            `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByGameIdResponse) Reset() {
	*x = FindByGameIdResponse{}
	mi := &file_proto_v1_question_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByGameIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByGameIdResponse) ProtoMessage() {}

func (x *FindByGameIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_question_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByGameIdResponse.ProtoReflect.Descriptor instead.
func (*FindByGameIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_question_proto_rawDescGZIP(), []int{8}
}

func (x *FindByGameIdResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

var File_proto_v1_question_proto protoreflect.FileDescriptor

const file_proto_v1_question_proto_rawDesc = "" +
	"\n" +
	"\x17proto/v1/question.proto\x12\vquestion.v1\"H\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04game\x18\x03 \x01(\tR\x04game\"\x10\n" +
	"\x0eFindAllRequest\"F\n" +
	"\x0fFindAllResponse\x123\n" +
	"\tquestions\x18\x01 \x03(\v2\x15.question.v1.QuestionR\tquestions\"B\n" +
	"\x12AddQuestionRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x12\n" +
	"\x04game\x18\x02 \x01(\tR\x04game\"H\n" +
	"\x13AddQuestionResponse\x121\n" +
	"\bquestion\x18\x01 \x01(\v2\x15.question.v1.QuestionR\bquestion\"4\n" +
	"\x19FindRandomQuestionRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\"O\n" +
	"\x1aFindRandomQuestionResponse\x121\n" +
	"\bquestion\x18\x01 \x01(\v2\x15.question.v1.QuestionR\bquestion\".\n" +
	"\x13FindByGameIdRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\"K\n" +
	"\x14FindByGameIdResponse\x123\n" +
	"\tquestions\x18\x01 \x03(\v2\x15.question.v1.QuestionR\tquestions2\xe5\x02\n" +
	"\x0fQuestionService\x12D\n" +
	"\aFindAll\x12\x1b.question.v1.FindAllRequest\x1a\x1c.question.v1.FindAllResponse\x12P\n" +
	"\vAddQuestion\x12\x1f.question.v1.AddQuestionRequest\x1a .question.v1.AddQuestionResponse\x12e\n" +
	"\x12FindRandomQuestion\x12&.question.v1.FindRandomQuestionRequest\x1a'.question.v1.FindRandomQuestionResponse\x12S\n" +
	"\fFindByGameId\x12 .question.v1.FindByGameIdRequest\x1a!.question.v1.FindByGameIdResponseB:Z8github.com/mobqom/questions/proto/v1/question;questionv1b\x06proto3"

var (
	file_proto_v1_question_proto_rawDescOnce sync.Once
	file_proto_v1_question_proto_rawDescData []byte
)

func file_proto_v1_question_proto_rawDescGZIP() []byte {
	file_proto_v1_question_proto_rawDescOnce.Do(func() {
		file_proto_v1_question_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_question_proto_rawDesc), len(file_proto_v1_question_proto_rawDesc)))
	})
	return file_proto_v1_question_proto_rawDescData
}

var file_proto_v1_question_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_v1_question_proto_goTypes = []any{
	(*Question)(nil),                   // 0: question.v1.Question
	(*FindAllRequest)(nil),             // 1: question.v1.FindAllRequest
	(*FindAllResponse)(nil),            // 2: question.v1.FindAllResponse
	(*AddQuestionRequest)(nil),         // 3: question.v1.AddQuestionRequest
	(*AddQuestionResponse)(nil),        // 4: question.v1.AddQuestionResponse
	(*FindRandomQuestionRequest)(nil),  // 5: question.v1.FindRandomQuestionRequest
	(*FindRandomQuestionResponse)(nil), // 6: question.v1.FindRandomQuestionResponse
	(*FindByGameIdRequest)(nil),        // 7: question.v1.FindByGameIdRequest
	(*FindByGameIdResponse)(nil),       // 8: question.v1.FindByGameIdResponse
}
var file_proto_v1_question_proto_depIdxs = []int32{
	0, // 0: question.v1.FindAllResponse.questions:type_name -> question.v1.Question
	0, // 1: question.v1.AddQuestionResponse.question:type_name -> question.v1.Question
	0, // 2: question.v1.FindRandomQuestionResponse.question:type_name -> question.v1.Question
	0, // 3: question.v1.FindByGameIdResponse.questions:type_name -> question.v1.Question
	1, // 4: question.v1.QuestionService.FindAll:input_type -> question.v1.FindAllRequest
	3, // 5: question.v1.QuestionService.AddQuestion:input_type -> question.v1.AddQuestionRequest
	5, // 6: question.v1.QuestionService.FindRandomQuestion:input_type -> question.v1.FindRandomQuestionRequest
	7, // 7: question.v1.QuestionService.FindByGameId:input_type -> question.v1.FindByGameIdRequest
	2, // 8: question.v1.QuestionService.FindAll:output_type -> question.v1.FindAllResponse
	4, // 9: question.v1.QuestionService.AddQuestion:output_type -> question.v1.AddQuestionResponse
	6, // 10: question.v1.QuestionService.FindRandomQuestion:output_type -> question.v1.FindRandomQuestionResponse
	8, // 11: question.v1.QuestionService.FindByGameId:output_type -> question.v1.FindByGameIdResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_v1_question_proto_init() }
func file_proto_v1_question_proto_init() {
	if File_proto_v1_question_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_question_proto_rawDesc), len(file_proto_v1_question_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_question_proto_goTypes,
		DependencyIndexes: file_proto_v1_question_proto_depIdxs,
		MessageInfos:      file_proto_v1_question_proto_msgTypes,
	}.Build()
	File_proto_v1_question_proto = out.File
	file_proto_v1_question_proto_goTypes = nil
	file_proto_v1_question_proto_depIdxs = nil
}
