basePath: /api/v1
consumes:
- application/json
definitions:
  domain.Option:
    properties:
      content:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      id:
        type: integer
      question_id:
        type: integer
      updated_at:
        type: string
    type: object
  domain.Question:
    properties:
      content:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      game:
        type: string
      id:
        type: integer
      options:
        items:
          $ref: '#/definitions/domain.Option'
        type: array
      updated_at:
        type: string
    type: object
  dto.AddOptionDto:
    properties:
      content:
        type: string
      question_id:
        type: integer
    required:
    - content
    - question_id
    type: object
  dto.AddQuestionDto:
    properties:
      content:
        type: string
      game:
        type: string
    required:
    - content
    - game
    type: object
host: localhost:8081
info:
  contact: {}
  description: API для работы с вопросами
  title: Questions API
  version: "1.0"
paths:
  /options/{questionId}:
    get:
      description: Возвращает список всех вариантов ответов для конкретного вопроса
      parameters:
      - description: ID вопроса
        in: path
        name: questionId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Option'
            type: array
      summary: Получить варианты ответов для вопроса
      tags:
      - options
  /options/add-option:
    post:
      consumes:
      - application/json
      description: Создает новый вариант ответа для вопроса
      parameters:
      - description: Объект варианта ответа
        in: body
        name: option
        required: true
        schema:
          $ref: '#/definitions/dto.AddOptionDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.Option'
        "400":
          description: Invalid request body
          schema:
            type: string
      summary: Добавить новый вариант ответа
      tags:
      - options
  /options/find-all:
    get:
      description: Возвращает список всех вариантов ответов из базы данных
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Option'
            type: array
      summary: Получить все варианты ответов
      tags:
      - options
  /questions/add-question:
    post:
      consumes:
      - application/json
      description: Создает новый вопрос в базе данных
      parameters:
      - description: Объект вопроса
        in: body
        name: question
        required: true
        schema:
          $ref: '#/definitions/dto.AddQuestionDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.Question'
        "400":
          description: Invalid request body
          schema:
            type: string
      summary: Добавить новый вопрос
      tags:
      - questions
  /questions/find-all:
    get:
      description: Возвращает список всех вопросов из базы данных
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Question'
            type: array
      summary: Получить все вопросы
      tags:
      - questions
  /questions/find-by-game:
    get:
      description: Возвращает список всех вопросов для конкретной игры
      parameters:
      - description: ID игры
        in: query
        name: gameId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Question'
            type: array
      summary: Получить вопросы по ID игры
      tags:
      - questions
  /questions/random:
    get:
      description: Возвращает случайный вопрос из базы данных
      parameters:
      - description: ID игры
        in: query
        name: gameId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Question'
      summary: Получить случайный вопрос
      tags:
      - questions
produces:
- application/json
schemes:
- http
swagger: "2.0"
