apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: app-deploy-template
  namespace: tekton-pipelines
spec:
  params:
    - name: git-repo-url
      description: URL of the git repository
    - name: git-revision
      description: Revision (branch, SHA)
      default: main
    - name: target-namespace
      description: Target Kubernetes namespace (dev or prod)
    - name: image-name
      description: Docker image name to build and deploy
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: app-cicd-pipeline-run-$(tt.params.target-namespace)-
        namespace: tekton-pipelines
      spec:
        pipelineRef:
          name: app-cicd-pipeline
        params:
          - name: REPO_URL
            value: $(tt.params.git-repo-url)
          - name: REPO_REVISION
            value: $(tt.params.git-revision)
          - name: IMAGE
            value: $(tt.params.image-name)
          - name: TARGET_NAMESPACE
            value: $(tt.params.target-namespace)
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 500Mi
