apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: github-dev-trigger
  namespace: tekton-pipelines
spec:
  interceptors:
    - ref:
        name: "cel"
      params:
        - name: "filter"
          value: "body.ref == 'refs/heads/dev'"
        - name: "overlays"
          value:
            - key: git_revision
              expression: "body.after"
            - key: git_repo_url
              expression: "body.repository.clone_url"
  bindings:
    - name: git-repo-url
      value: $(extensions.git_repo_url)
    - name: git-revision
      value: $(extensions.git_revision)
    - name: target-namespace
      value: "dev"
    - name: image-name
      value: "my-app:dev-$(extensions.git_revision)"
  template:
    ref: app-deploy-template
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: github-prod-trigger
  namespace: tekton-pipelines
spec:
  interceptors:
    - ref:
        name: "cel"
      params:
        - name: "filter"
          value: "body.ref == 'refs/heads/main' || body.ref == 'refs/heads/master'"
        - name: "overlays"
          value:
            - key: git_revision
              expression: "body.after"
            - key: git_repo_url
              expression: "body.repository.clone_url"
  bindings:
    - name: git-repo-url
      value: $(extensions.git_repo_url)
    - name: git-revision
      value: $(extensions.git_revision)
    - name: target-namespace
      value: "prod"
    - name: image-name
      value: "my-app:prod-$(extensions.git_revision)"
  template:
    ref: app-deploy-template
